# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RidlLsp < Formula
  desc "Language server for RIDL schema files"
  homepage "https://github.com/webrpc/ridl-lsp"
  version "1.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/webrpc/ridl-lsp/releases/download/v1.2.2/ridl-lsp.darwin-amd64"
      sha256 "edba22560bf9d8a517e3a9df20ee2f976d53bec0219f95691f3403e0e2ffa83c"

      define_method(:install) do
        bin.install "ridl-lsp.darwin-amd64" => "ridl-lsp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/webrpc/ridl-lsp/releases/download/v1.2.2/ridl-lsp.darwin-arm64"
      sha256 "b54a3f5159fc6991c9bf853ee25bf9c7cc0ffc896282ae695691604f269b7059"

      define_method(:install) do
        bin.install "ridl-lsp.darwin-arm64" => "ridl-lsp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/webrpc/ridl-lsp/releases/download/v1.2.2/ridl-lsp.linux-amd64"
      sha256 "695ce218cc351ebda79c04289be2951840ec07c034c5c08f7f396af5cf690261"
      define_method(:install) do
        bin.install "ridl-lsp.linux-amd64" => "ridl-lsp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/webrpc/ridl-lsp/releases/download/v1.2.2/ridl-lsp.linux-arm64"
      sha256 "5f07fc248a3f5c0ab1cb2e069a951543828c0564210baa74439662c3adfad604"
      define_method(:install) do
        bin.install "ridl-lsp.linux-arm64" => "ridl-lsp"
      end
    end
  end
end
