# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RidlLsp < Formula
  desc "Language server for RIDL schema files"
  homepage "https://github.com/webrpc/ridl-lsp"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/webrpc/ridl-lsp/releases/download/v1.3.0/ridl-lsp.darwin-amd64"
      sha256 "1d69710f1bb9defa9aac1251aa1c24ead6e8836b81a89b2d173f9deaf0ec3d15"

      define_method(:install) do
        bin.install "ridl-lsp.darwin-amd64" => "ridl-lsp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/webrpc/ridl-lsp/releases/download/v1.3.0/ridl-lsp.darwin-arm64"
      sha256 "811fe31bc818f340167a1f9ab791db9151e6fba39657d6a54466dc38283c8a60"

      define_method(:install) do
        bin.install "ridl-lsp.darwin-arm64" => "ridl-lsp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/webrpc/ridl-lsp/releases/download/v1.3.0/ridl-lsp.linux-amd64"
      sha256 "2dd3a70887e54d211d8e4af31f3da0a1816ecc5edf035fc4ee734eaeff1958a9"
      define_method(:install) do
        bin.install "ridl-lsp.linux-amd64" => "ridl-lsp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/webrpc/ridl-lsp/releases/download/v1.3.0/ridl-lsp.linux-arm64"
      sha256 "8652f91925be5a8e4f87718b78a0fdc2cfa624cf978e777c9ccabe859a44055e"
      define_method(:install) do
        bin.install "ridl-lsp.linux-arm64" => "ridl-lsp"
      end
    end
  end
end
