# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WebrpcGen < Formula
  desc "generate source code for your target language from webrpc schema"
  homepage "https://github.com/webrpc/webrpc"
  version "0.9.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/webrpc/webrpc/releases/download/v0.9.2/webrpc-gen.darwin-amd64"
      sha256 "21a4e8a92f86b7db38d629237f5a316c9e3862fd30a421a13f1e9dab4bcfdced"

      def install
        bin.install "webrpc-gen.darwin-amd64" => "webrpc-gen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/webrpc/webrpc/releases/download/v0.9.2/webrpc-gen.darwin-arm64"
      sha256 "6181dd5a8b205a41c1b142b38d1fe9db48f417b6925592fe1160d92968b5db94"

      def install
        bin.install "webrpc-gen.darwin-arm64" => "webrpc-gen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/webrpc/webrpc/releases/download/v0.9.2/webrpc-gen.linux-amd64"
      sha256 "0d4f9caad5c09352cc4f827ff437a9c458245fbbf5b7e3892ff75edb16844008"

      def install
        bin.install "webrpc-gen.linux-amd64" => "webrpc-gen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/webrpc/webrpc/releases/download/v0.9.2/webrpc-gen.linux-arm64"
      sha256 "c6e0a1455f35609bbe447e19da8e3eb6677893fd61c6aada37b809e95317c1b8"

      def install
        bin.install "webrpc-gen.linux-arm64" => "webrpc-gen"
      end
    end
  end
end
