# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WebrpcGen < Formula
  desc "generate source code for your target language from webrpc schema"
  homepage "https://github.com/webrpc/webrpc"
  version "0.30.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/webrpc/webrpc/releases/download/v0.30.2/webrpc-gen.darwin-amd64"
      sha256 "18dd73d9550400197178d4dd5c27342ea2a5202770d643875d0fcdf6b5e36d64"

      def install
        bin.install "webrpc-gen.darwin-amd64" => "webrpc-gen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/webrpc/webrpc/releases/download/v0.30.2/webrpc-gen.darwin-arm64"
      sha256 "b08d954bed3dbe5b95238d9c61beeecbd1333718ee7a33e6f0a0dece259e776e"

      def install
        bin.install "webrpc-gen.darwin-arm64" => "webrpc-gen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/webrpc/webrpc/releases/download/v0.30.2/webrpc-gen.linux-amd64"
      sha256 "bd81db0c16c4109c1afd2a71b0352cae44809011bed41b5eea71fb197c108cec"
      def install
        bin.install "webrpc-gen.linux-amd64" => "webrpc-gen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/webrpc/webrpc/releases/download/v0.30.2/webrpc-gen.linux-arm64"
      sha256 "83b740162de16d7516da3626da13272bea155638c24160caf4a758091ac23041"
      def install
        bin.install "webrpc-gen.linux-arm64" => "webrpc-gen"
      end
    end
  end
end
